try {

    VERSION = "0.0.1"
    SERVERLESS_IMAGE = ""

    pipeline {
    
        parameters{
            choice(
                choices: 'patch\nminor\nmajor',
                description: "Version update type"
            )
        }

        node{
            
            stage("Cleanup") {
                deleteDir()
            }

            stage("Project Checkout") {
                checkout scm
            }

            stage("Create Tag"){

            }

            stage("Get Secrets") {
                //get google api key from s3 bucket
                //sed into serverless.yml
            }

            stage("Build Docker image"){
                docker.build("serverless:${VERSION}")
            }

            stage("Release Docker image"){

            }

            stage("Release Tag"){

            }

            stage("Deploy Serverless Instance") {
                docker.image("${SERVERLESS_IMAGE}").inside(){
                    sh "sls deploy"
                }
            }
        }
    }
} catch(Exception e){
    throw e
} finally{

}
