try {
    pipeline {

        agent any
        environment {

        }

        stages {
            stage("Cleanup") {
                steps{

                }
            }

            stage("Project Checkout") {
                steps{
                    checkout scm
                }
            }

            stage("Build Serverless Instance") {
                steps{
                    
                }//sls create_domain
            }

            stage("Deploy Serverless Instance") {
                steps{
                    
                }//sls deploy
            }
        }
    }
} catch(Exception e){
    throw e
} finally{

}