# serverless.yml

service: drewgrubb-test-api

provider:
  name: aws
  runtime: python3.6
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "execute-api:Invoke"
      Resource:
        - "arn:aws:execute-api:*:*:*"

functions:
  patent:
    handler: functions/patent_handler.main
    timeout: 5
    memorySize: 128
    environment:
      api_key: "k"
    events:
#      - schedule: rate(15 minutes)
      - http:
          path: patent
          method: get
          cors: true

resources:
  Resources:
    SecretsBucket:
      Type: "AWS::S3::Bucket"
    
    
