# serverless.yml

service: drewgrubb-test-api

provider:
  name: aws
  runtime: python3.6
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "execute-api:Invoke"
      Resource:
        - "arn:aws:execute-api:*:*:*"

functions:
  maps:
    handler: maps_handler.main
    timeout: 5
    memorySize: 128
    environment:
      api-key: "__api-key__"
    events:
      - schedule: rate(15 minutes)
      - http:
          path: test
          method: get
          cors: true

resources:
  Resources:
